### ISSUE TITLE
Implement a motor hardware interface on the Arduino to read encoder values, send, and write motor speeds.

### ISSUE THREAD

**Issue by AndrewChen26** [phgandhi02/f1tenth_amr#3]
The easiest way is to write your own bridge the main idea would be to have something that reads the digital signal from the encoder and publishes it, sends current motor speed, and writes motor speed to the motors as a PWM signal. 

The message will be passed via Serial although I would like to investigate the I2C communication protocol. This will make it easier to expand the message that we need to send. Start with Serial message.

Problem breakdown:

- [x] Make a simple reader.
- [x] Make a simple PWM signal based on a static signal
- [x] make a simple input interface.
- [x] read the encoder signals
- [x] calculate the position and the velocity
- [x] publish as a ROS message.

**Comment by AndrewChen26** [comment]
This link shows how to use I2C between arduino and raspberry pi.
https://dronebotworkshop.com/i2c-arduino-raspberry-pi/

This link shows how to set up serial communication between arduino and RasPi.
https://roboticsbackend.com/raspberry-pi-arduino-serial-communication/

**Comment by phgandhi02** [comment]
Here is a tinkercad file that you can test out your ideas on: 
https://www.tinkercad.com/things/9iAAho9YWIz-swanky-habbi-densor

**Comment by phgandhi02** [comment]
Here's how to write serial to the Arduino: https://projecthub.arduino.cc/ansh2919/serial-communication-between-python-and-arduino-663756

**Comment by phgandhi02** [comment]
This issue was resolved by using the ros_arduino_bridge library on the arduino. Would like to develop a custom solution for personal knowledge later on.
